/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Materialization Configuration. The incremental object form accepts `format` (delta_lake | hive | iceberg), `partitions`, `strategy`, `database`, and the physical-layout tuning fields `bucket` and `sorted_by`. DJ translates `bucket` / `sorted_by` into the correct Trino table properties per format: Iceberg emits bucket transforms inside `partitioning` plus a standalone `sorted_by`; Hive / Glue emits `bucketed_by` + `bucket_count` + `sorted_by`; Delta Lake supports neither and DJ flags it.
 */
export type SchemaModelMaterialization =
  | 'incremental'
  | 'ephemeral'
  | {
      type: 'ephemeral';
    }
  | {
      type: 'incremental';
      database?: SchemaModelDatabase;
      format?: SchemaModelFormat;
      partitions?: SchemaModelPartitions;
      bucket?: SchemaModelBucket;
      sorted_by?: SchemaModelSortedBy;
      strategy?: IncrementalStrategy;
    };
/**
 * Database override for where the model will be materialized
 */
export type SchemaModelDatabase = string;
/**
 * Open table format for the model
 */
export type SchemaModelFormat = 'delta_lake' | 'hive' | 'iceberg';
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Override the default partitioneds configuration for this model
 */
export type SchemaModelPartitions = SchemaColumnName[];
/**
 * Bucketing configuration for the materialized table. Accepts a single { column, count } object or an array of them. On Iceberg, each entry is emitted as a bucket(column, count) transform inside `partitioning`. On Hive / Glue, columns are emitted as `bucketed_by` with a single shared `bucket_count` (all entries must share the same count). Not supported on Delta Lake in dbt-trino.
 */
export type SchemaModelBucket = BucketSpec | [BucketSpec, ...BucketSpec[]];
/**
 * Columns to sort table data by within each written file (the `sorted_by` Trino table property). On Iceberg this is a standalone sort order. On Hive / Glue it determines the sort order within each bucket and requires `bucket` to also be set. Not supported on Delta Lake in dbt-trino. Column ordering is ascending; `col DESC` style ordering is not supported.
 *
 * @minItems 1
 */
export type SchemaModelSortedBy = [SchemaColumnName, ...SchemaColumnName[]];
/**
 * Incremental Strategy for dbt-trino. Pick one of: 'append', 'delete+insert', 'merge', 'overwrite_existing_partitions', 'dj_iceberg_partition_overwrite'. NOTE: 'overwrite_existing_partitions' requires a custom dbt macro in your project and is not shipped by the DJ (Data JSON) Framework. 'merge' and 'dj_iceberg_partition_overwrite' require the target table to use Iceberg format in dbt-trino. When in doubt, use 'delete+insert' with a partition column as unique_key.
 */
export type IncrementalStrategy =
  | {
      /**
       * Append rows without de-duplication.
       */
      type: 'append';
    }
  | {
      /**
       * Delete rows matching unique_key, then insert.
       */
      type: 'delete+insert';
      /**
       * Override the unique key(s) to use for delete+insert. Defaults to the model's partition column when omitted.
       */
      unique_key?: string | [string, ...string[]];
    }
  | {
      /**
       * Row-level upsert on unique_key. Requires Iceberg in dbt-trino.
       */
      type: 'merge';
      /**
       * The unique key(s) to use for merging.
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging.
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging.
       */
      merge_update_columns?: string[];
    }
  | {
      /**
       * Overwrite only the partitions in the new slice. REQUIRES a custom macro in your dbt project — prefer 'delete+insert' if you do not have one.
       */
      type: 'overwrite_existing_partitions';
    }
  | {
      /**
       * Overwrite only the partitions in the new slice on an Iceberg table. Shipped by DJ; requires Iceberg format.
       */
      type: 'dj_iceberg_partition_overwrite';
    };

/**
 * A single bucketing column and its bucket count.
 */
export interface BucketSpec {
  column: SchemaColumnName;
  /**
   * Number of hash buckets to distribute the column's values across.
   */
  count: number;
}
