/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bucketing configuration for the materialized table. Accepts a single { column, count } object or an array of them. On Iceberg, each entry is emitted as a bucket(column, count) transform inside `partitioning`. On Hive / Glue, columns are emitted as `bucketed_by` with a single shared `bucket_count` (all entries must share the same count). Not supported on Delta Lake in dbt-trino.
 */
export type SchemaModelBucket = BucketSpec | [BucketSpec, ...BucketSpec[]];
/**
 * Validate column name
 */
export type SchemaColumnName = string;

/**
 * A single bucketing column and its bucket count.
 */
export interface BucketSpec {
  column: SchemaColumnName;
  /**
   * Number of hash buckets to distribute the column's values across.
   */
  count: number;
}
