/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Columns to sort table data by within each written file (the `sorted_by` Trino table property). On Iceberg this is a standalone sort order. On Hive / Glue it determines the sort order within each bucket and requires `bucket` to also be set. Not supported on Delta Lake in dbt-trino. Column ordering is ascending; `col DESC` style ordering is not supported.
 *
 * @minItems 1
 */
export type SchemaModelSortedBy = [SchemaColumnName, ...SchemaColumnName[]];
/**
 * Validate column name
 */
export type SchemaColumnName = string;
