/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Controls auto-injection of the portal partition date columns. `true` drops all of them (`portal_partition_monthly`, `portal_partition_daily`, `portal_partition_hourly`); `false` or omitted keeps all. Provide an array of partition column names (e.g. ["portal_partition_hourly"]) to drop only those while keeping the rest. An array overrides `exclude_framework_artifacts` at the same scope, narrowing its all-partitions exclusion to just the listed columns. Columns you list explicitly in `select` are always kept.
 */
export type SchemaModelExcludePortalPartitionColumns =
  | boolean
  | [
      (
        | 'portal_partition_monthly'
        | 'portal_partition_daily'
        | 'portal_partition_hourly'
      ),
      ...(
        | 'portal_partition_monthly'
        | 'portal_partition_daily'
        | 'portal_partition_hourly'
      )[],
    ];
