/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single upstream lineage source for a Python model output table
 */
export interface SchemaPythonModelUpstreamSource {
  /**
   * trino = Iceberg/Hive table (schema.table); external = non-Trino source
   */
  type: 'trino' | 'external';
  /**
   * trino: schema.table; external: free-form identifier (API name, S3 path, etc.)
   */
  value: string;
}
