/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate Python model name
 */
export type SchemaPythonModelName = string;
/**
 * Validate Python model group (team/project)
 */
export type SchemaPythonModelGroup = string;
/**
 * Validate Python model topic
 */
export type SchemaPythonModelTopic = string;
/**
 * Validate Python model description
 */
export type SchemaPythonModelDescription = string;
/**
 * Validate Python model tags array
 */
export type SchemaPythonModelTags = string[];

/**
 * Validates schema for Python model configuration files
 */
export interface SchemaPythonModel {
  name: SchemaPythonModelName;
  group: SchemaPythonModelGroup;
  topic: SchemaPythonModelTopic;
  description?: SchemaPythonModelDescription;
  /**
   * Model execution type (always python)
   */
  model_type?: 'python';
  /**
   * DAGs to integrate this model with (e.g., source_etl). Leave empty for importable utility models.
   */
  dags?: string[];
  /**
   * Names of other Python models that must complete before this model runs
   */
  depends_on?: string[];
  /**
   * Output backend type for data writes
   */
  output_type?: 'iceberg' | 's3';
  output?: {
    /**
     * Target database name (optional)
     */
    database?: string;
    /**
     * Target schema name (optional)
     */
    schema?: string;
    /**
     * Target table name (optional)
     */
    table?: string;
    /**
     * Partition columns
     */
    partition_by?: string[];
    /**
     * Write mode for data loading
     */
    write_mode?: 'append' | 'overwrite' | 'overwrite_partitions';
  };
  /**
   * Generate .python.ipynb notebook file
   */
  enable_notebook?: boolean;
  /**
   * Python package dependencies (e.g., requests>=2.28.0)
   */
  dependencies?: string[];
  tags?: SchemaPythonModelTags;
  /**
   * Owner team or individual
   */
  owner?: string;
  /**
   * Iceberg namespace for the output table (default: python)
   */
  namespace?: string;
  /**
   * Iceberg table name (default: same as model name)
   */
  table_name?: string;
  /**
   * Notebook cells snapshot persisted from the .python.ipynb view (the .python.py file remains the source of truth for code)
   */
  cells?: {
    cell_type: 'markdown' | 'code' | 'raw';
    metadata?: {
      [k: string]: unknown | undefined;
    };
    source: string[] | string;
    outputs?: unknown[];
    execution_count?: unknown;
    [k: string]: unknown | undefined;
  }[];
  /**
   * Environment variables (e.g., S3 bucket, API endpoints)
   */
  variables?: {
    [k: string]: string | undefined;
  };
}
