import type {
  PythonModelCell,
  PythonModelConfig,
} from '@shared/framework/types';

/**
 * Generate the shared python_models/_config.py module.
 * Contains PythonModelConfig dataclass + catalog/namespace helpers.
 * Created once per project.
 */
export function generatePythonModelConfigPy(): string {
  return `"""
Shared configuration for Python models.
Auto-generated by DJ Framework -- safe to extend, do not delete.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class PythonModelConfig:
    model_name: str
    namespace: str = "python"
    table_name: str = ""
    model_type: str = "python"
    description: str = ""

    @property
    def table_id(self) -> str:
        return f"{self.namespace}.{self.table_name or self.model_name}"

    @property
    def full_table_id(self) -> str:
        return f"iceberg_catalog.{self.table_id}"

    @property
    def table_properties(self) -> dict[str, str]:
        return {
            "python_model_name": self.model_name,
            "python_model_type": self.model_type,
            "python_model_namespace": self.namespace,
            "python_model_table": self.table_name or self.model_name,
            "python_model_description": self.description,
        }


def get_catalog():
    """Return a PyIceberg catalog. Override constants for your environment."""
    try:
        from pyiceberg.catalog import load_catalog
    except ImportError:
        raise ImportError("pyiceberg is required: pip install pyiceberg")

    CATALOG_CONFIG = {
        "type": "hive",
        "uri": "thrift://hive-metastore:9083",
        "s3.endpoint": "http://minio:9000",
        "s3.access-key-id": "minioadmin",
        "s3.secret-access-key": "minioadmin",
    }
    return load_catalog("iceberg_catalog", **CATALOG_CONFIG)


def ensure_namespace(catalog, namespace: str) -> None:
    """Create an Iceberg namespace if it doesn't exist."""
    try:
        catalog.create_namespace(namespace)
    except Exception:
        pass
`;
}

/** @deprecated Use generatePythonModelConfigPy */
export const generatePredbtConfigPy = generatePythonModelConfigPy;

const SECTION_SEP =
  '# ============================================================';

function buildModelVariablesSource(config: PythonModelConfig): string[] {
  const vars: Record<string, string> = {
    name: config.name,
    group: config.group,
    topic: config.topic,
    description: config.description ?? '',
    ...(config.variables ?? {}),
  };

  const lines: string[] = [
    `${SECTION_SEP}\n`,
    '# INPUT VARIABLES\n',
    `${SECTION_SEP}\n`,
    'INPUT_VARIABLES = {\n',
  ];
  for (const [key, value] of Object.entries(vars)) {
    lines.push(`    "${key}": "${value}",\n`);
  }
  lines.push('}\n');
  return lines;
}

/**
 * Generate the default notebook-format cells for a new Python model.
 * These cells are stored in .python.json and used to derive .py and .ipynb.
 */
export function generatePythonModelCells(
  config: PythonModelConfig,
): PythonModelCell[] {
  const { name, group, topic, description } = config;
  const dags = config.dags ?? [];
  const namespace = config.namespace ?? 'python';
  const tableName = config.table_name ?? name;
  const outputType = config.output_type ?? 'iceberg';

  const modelId = `python__${group}__${topic}__${name}`;
  const dagsStr = dags.length > 0 ? dags.join(', ') : '(none)';

  const importLines: string[] = [
    'from datetime import datetime\n',
    'import io\n',
    'import json\n',
    'import logging\n',
    '\n',
    'import pandas as pd\n',
  ];
  if (outputType === 's3') {
    importLines.push('import boto3\n');
  }

  const cells: PythonModelCell[] = [
    {
      cell_type: 'markdown',
      metadata: {},
      source: [`# Python Model: ${modelId}\n`, `**DAGs**: ${dagsStr}\n`],
    },
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        ...importLines,
        '\n',
        'log = logging.getLogger(__name__)\n',
        '\n',
        'context = {\n',
        "    'ds': datetime.now().strftime('%Y-%m-%d'),\n",
        "    'ds_nodash': datetime.now().strftime('%Y%m%d'),\n",
        '}\n',
      ],
    },
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        'from python_models._config import PythonModelConfig\n',
        '\n',
        'OUTPUT_CONFIG = PythonModelConfig(\n',
        `    model_name="${name}",\n`,
        `    namespace="${namespace}",\n`,
        `    table_name="${tableName}",\n`,
        `    model_type="python",\n`,
        `    description="${description ?? ''}",\n`,
        ')\n',
      ],
    },
    // INPUT_VARIABLES (with section header)
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: buildModelVariablesSource(config),
    },
    // EXTRACT
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        `${SECTION_SEP}\n`,
        '# EXTRACT\n',
        `${SECTION_SEP}\n`,
        'def extract(context: dict) -> pd.DataFrame:\n',
        '    """Fetch data from source."""\n',
        '    log.info(f"Extracting for {context[\'ds\']}...")\n',
        '    raise NotImplementedError("Implement extract()")\n',
      ],
    },
    // TRANSFORM
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        `${SECTION_SEP}\n`,
        '# TRANSFORM\n',
        `${SECTION_SEP}\n`,
        'def transform(df: pd.DataFrame, context: dict) -> pd.DataFrame:\n',
        '    """Clean and enrich data."""\n',
        '    if df is None or df.empty:\n',
        '        return pd.DataFrame()\n',
        '\n',
        "    df['portal_partition_daily'] = context['ds']\n",
        '\n',
        '    return df\n',
      ],
    },
    // LOAD (conditional on output_type)
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source:
        outputType === 's3'
          ? [
              `${SECTION_SEP}\n`,
              '# LOAD\n',
              `${SECTION_SEP}\n`,
              'def load(df: pd.DataFrame, context: dict) -> None:\n',
              '    """Upload data to S3."""\n',
              '    if df is None or df.empty:\n',
              '        log.warning("No data to load")\n',
              '        return\n',
              '\n',
              '    s3 = boto3.client("s3")\n',
              '    bucket = INPUT_VARIABLES.get("s3_bucket", "your-bucket")\n',
              "    key = f\"{INPUT_VARIABLES.get('s3_prefix', 'data')}/{context['ds']}/output.json\"\n",
              '\n',
              '    log.info(f"Uploading {len(df)} rows to s3://{bucket}/{key}")\n',
              '    s3.put_object(Bucket=bucket, Key=key, Body=df.to_json(orient="records"))\n',
            ]
          : [
              `${SECTION_SEP}\n`,
              '# LOAD\n',
              `${SECTION_SEP}\n`,
              'def load(df: pd.DataFrame, context: dict) -> None:\n',
              '    """Save data to destination."""\n',
              '    if df is None or df.empty:\n',
              '        log.warning("No data to load")\n',
              '        return\n',
              '\n',
              '    log.info(f"Loading {len(df)} rows...")\n',
              '    raise NotImplementedError("Implement load()")\n',
            ],
    },
    // POST-LOAD
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        `${SECTION_SEP}\n`,
        '# POST-LOAD (optional)\n',
        `${SECTION_SEP}\n`,
        'def post_load(context: dict) -> None:\n',
        '    """Sync partitions or cleanup."""\n',
        '    pass\n',
      ],
    },
    // MAIN
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: [
        `${SECTION_SEP}\n`,
        '# MAIN\n',
        `${SECTION_SEP}\n`,
        'def run_etl(context: dict):\n',
        '    """Main ETL orchestrator."""\n',
        '    df = extract(context)\n',
        '    df = transform(df, context)\n',
        '    load(df, context)\n',
        '    post_load(context)\n',
      ],
    },
    // Notebook-only: runner cell
    {
      cell_type: 'code',
      execution_count: null,
      metadata: {},
      outputs: [],
      source: ['# Run the ETL\n', 'run_etl(context)\n'],
    },
  ];

  return cells;
}

/**
 * Convert cells to a Python (.python.py) file.
 * Extracts code cells, skips the notebook-only setup cell (context dict)
 * and the runner cell, producing a clean Python module.
 */
export function cellsToPython(
  cells: PythonModelCell[],
  config: PythonModelConfig,
): string {
  const { name, group, topic } = config;
  const dags = config.dags ?? [];
  const modelId = `python__${group}__${topic}__${name}`;
  const dagsStr = dags.length > 0 ? dags.join(', ') : '(none)';

  const codeCells = cells.filter((c) => c.cell_type === 'code');
  const lines: string[] = [];

  lines.push(`"""\nPython Model: ${modelId}\nDAGs: ${dagsStr}\n"""`);

  for (const cell of codeCells) {
    const src = Array.isArray(cell.source) ? cell.source.join('') : cell.source;
    const trimmed = src.trim();

    // Skip the notebook-only runner cell
    if (
      trimmed === 'run_etl(context)' ||
      trimmed === '# Run the ETL\nrun_etl(context)'
    ) {
      continue;
    }

    // For the imports+context setup cell, extract only the import/log lines
    if (trimmed.includes('context = {')) {
      const importLines = trimmed
        .split('\n')
        .filter(
          (l) =>
            !l.startsWith('context') &&
            !l.startsWith("    '") &&
            !l.startsWith('}') &&
            l.trim() !== '',
        )
        .join('\n');
      if (importLines.trim()) {
        lines.push(importLines.trim());
      }
      continue;
    }

    lines.push(trimmed);
  }

  return lines.join('\n\n\n') + '\n';
}

/**
 * Convert cells to a Jupyter notebook (.python.ipynb) JSON string.
 */
export function cellsToNotebook(cells: PythonModelCell[]): string {
  const nbCells = cells.map((cell) => {
    const base: Record<string, unknown> = {
      cell_type: cell.cell_type,
      metadata: cell.metadata ?? {},
      source: cell.source,
    };
    if (cell.cell_type === 'code') {
      base.execution_count = cell.execution_count ?? null;
      base.outputs = cell.outputs ?? [];
    }
    return base;
  });

  const notebook = {
    cells: nbCells,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.9.0',
      },
    },
    nbformat: 4,
    nbformat_minor: 2,
  };

  return JSON.stringify(notebook, null, 2);
}

/**
 * Generates a Python model file (.python.py).
 * If config has cells, derives from them. Otherwise uses the default template.
 */
export function generatePythonModel(config: PythonModelConfig): string {
  if (config.cells && config.cells.length > 0) {
    return cellsToPython(config.cells, config);
  }

  const cells = generatePythonModelCells(config);
  return cellsToPython(cells, config);
}

/**
 * Generates a Jupyter notebook (.python.ipynb).
 * If config has cells, derives from them. Otherwise uses default cells.
 */
export function generatePythonModelNotebook(config: PythonModelConfig): string {
  if (config.cells && config.cells.length > 0) {
    return cellsToNotebook(config.cells);
  }

  const cells = generatePythonModelCells(config);
  return cellsToNotebook(cells);
}

/** @deprecated Use generatePythonModelCells */
export const generatePredbtCells = generatePythonModelCells;
/** @deprecated Use generatePythonModel */
export const generatePredbtModel = generatePythonModel;
/** @deprecated Use generatePythonModelNotebook */
export const generatePredbtNotebook = generatePythonModelNotebook;
