/**
 * Pure string transforms that inject register_python_model_tasks wiring
 * into existing Airflow DAG source. Kept separate from Framework so the
 * @dag and with DAG(...) shapes can be unit-tested without VS Code APIs.
 */

const ETL_HELPER_IMPORT =
  'from _ext_.etl_helper import register_python_model_tasks\n';

/**
 * Ensure the etl_helper import is present. Returns the updated source.
 */
export function ensureRegisterPythonModelTasksImport(dagCode: string): string {
  if (
    dagCode.includes('from _ext_.etl_helper import') ||
    dagCode.includes('from python_models import') ||
    dagCode.includes('from _ext_.python_models import')
  ) {
    return dagCode;
  }

  // Prefer inserting after other _ext_ imports
  const extImportMatch = dagCode.match(/from _ext_\.\w+ import[^;]+\n/g);
  if (extImportMatch && extImportMatch.length > 0) {
    const lastExtImport = extImportMatch[extImportMatch.length - 1];
    const insertPos = dagCode.indexOf(lastExtImport) + lastExtImport.length;
    return (
      dagCode.slice(0, insertPos) + ETL_HELPER_IMPORT + dagCode.slice(insertPos)
    );
  }

  // Fallback: insert after last import line
  const importLines = dagCode.match(/^(?:from |import ).+$/gm);
  if (importLines && importLines.length > 0) {
    const lastImport = importLines[importLines.length - 1];
    const insertPos = dagCode.indexOf(lastImport) + lastImport.length;
    return (
      dagCode.slice(0, insertPos) +
      '\n' +
      ETL_HELPER_IMPORT +
      dagCode.slice(insertPos)
    );
  }

  return ETL_HELPER_IMPORT + dagCode;
}

/**
 * Inject tasks into a @dag decorator-style DAG file.
 */
export function injectTasksDecoratorStyle(dagCode: string): string {
  const dagIdMatch = dagCode.match(/dag_id\s*=\s*["']([^"']+)["']/);
  const dagId = dagIdMatch?.[1] ?? 'unknown';

  const taskDefinitions = `
    # ── PYTHON MODELS (auto-generated by DJ Framework) ──

    entry_tasks, exit_tasks = register_python_model_tasks("${dagId}")

`;

  const sequenceMarker = dagCode.indexOf('# Sequence tasks');
  const taskInstantiationMarker = dagCode.match(
    /_start_etl\s*=\s*start_etl\(\)/,
  );

  if (sequenceMarker !== -1) {
    dagCode =
      dagCode.slice(0, sequenceMarker) +
      taskDefinitions +
      dagCode.slice(sequenceMarker);
  } else if (taskInstantiationMarker) {
    const insertPos = taskInstantiationMarker.index!;
    dagCode =
      dagCode.slice(0, insertPos) + taskDefinitions + dagCode.slice(insertPos);
  }

  // Strip legacy fetch/run_python_models wiring if present
  dagCode = dagCode.replace(
    /\s*_models = fetch_python_models\(\)\s*\n\s*_run = run_python_models\.expand\(model=_models\)\s*\n/g,
    '\n',
  );

  dagCode = dagCode.replace(
    /(\s*)_start >> _models >> _run >> _end/g,
    '$1_start >> entry_tasks\n$1exit_tasks >> _end',
  );

  const createSourceTablesMatch = dagCode.match(
    /_create_source_tables\s*=\s*create_source_tables\(\)\n/,
  );
  if (createSourceTablesMatch?.index !== undefined) {
    const insertPos =
      createSourceTablesMatch.index + createSourceTablesMatch[0].length;
    const taskInstantiation = `    entry_tasks, exit_tasks = register_python_model_tasks("${dagId}")
`;
    dagCode =
      dagCode.slice(0, insertPos) +
      taskInstantiation +
      dagCode.slice(insertPos);
  }

  const fetchSourcesPattern = />> _fetch_sources\n/;
  if (fetchSourcesPattern.test(dagCode)) {
    dagCode = dagCode.replace(
      fetchSourcesPattern,
      '>> entry_tasks >> exit_tasks\n        >> _fetch_sources\n',
    );
  }

  return dagCode;
}

/**
 * Inject tasks into a `with DAG(...)` context-manager-style DAG file.
 */
export function injectTasksContextManagerStyle(dagCode: string): string {
  const dagIdMatch = dagCode.match(/dag_id\s*=\s*["']([^"']+)["']/);
  const dagId = dagIdMatch?.[1] ?? 'unknown';

  // Ensure PythonOperator import (optional when using explicit dag=)
  if (!dagCode.includes('from airflow.operators.python')) {
    const importLine = 'from airflow.operators.python import PythonOperator\n';
    const importLines = dagCode.match(/^(?:from |import ).+$/gm);
    if (importLines && importLines.length > 0) {
      const lastImport = importLines[importLines.length - 1];
      const insertPos = dagCode.indexOf(lastImport) + lastImport.length;
      dagCode =
        dagCode.slice(0, insertPos) +
        '\n' +
        importLine +
        dagCode.slice(insertPos);
    }
  }

  // Detect indentation from the with block body
  const withBodyMatch = dagCode.match(
    /with\s+DAG\s*\([^)]*\)[^:]*:\s*\n(\s+)/s,
  );
  const indent = withBodyMatch ? withBodyMatch[1] : '    ';

  const taskDefs = [
    '',
    `${indent}# ── PYTHON MODELS (auto-generated by DJ Framework) ──`,
    `${indent}entry_tasks, exit_tasks = register_python_model_tasks("${dagId}", dag)`,
    '',
  ].join('\n');

  // Find the last >> chain (dependency chain) in the file
  const chainPattern = /^(\s*\S+\s*(?:>>\s*\S+\s*)+)$/gm;
  let lastChainMatch: RegExpExecArray | null = null;
  let match: RegExpExecArray | null;
  while ((match = chainPattern.exec(dagCode)) !== null) {
    lastChainMatch = match;
  }

  if (lastChainMatch) {
    const chainLine = lastChainMatch[0];
    const chainPos = lastChainMatch.index;

    // Insert task definitions before the chain line
    dagCode =
      dagCode.slice(0, chainPos) + taskDefs + '\n' + dagCode.slice(chainPos);

    // Split entry/exit: upstream operators >> python entry roots; python exits >> last operator
    const parts = chainLine.trim().split(/\s*>>\s*/);
    if (parts.length >= 2) {
      const lastOp = parts[parts.length - 1];
      const beforeLast = parts.slice(0, -1).join(' >> ');
      const chainIndent = chainLine.match(/^\s*/)?.[0] ?? indent;
      const bridge = `${chainIndent}${beforeLast} >> entry_tasks\n${chainIndent}exit_tasks >> ${lastOp}`;
      dagCode = dagCode.replace(chainLine, bridge);
    }
  } else {
    // No chain found -- just append task definitions before last line of the with block
    const withBlockEnd = dagCode.lastIndexOf('\n');
    if (withBlockEnd !== -1) {
      dagCode =
        dagCode.slice(0, withBlockEnd) + taskDefs + dagCode.slice(withBlockEnd);
    }
  }

  return dagCode;
}

/**
 * Build the proposed DAG source after injection, without writing.
 * Returns null when the file already has register_python_model_tasks wiring.
 */
export function buildInjectedDagSource(dagCode: string): {
  next: string;
  style: 'decorator' | 'context-manager' | 'imports-only';
} | null {
  if (dagCode.includes('register_python_model_tasks(')) {
    return null;
  }

  let next = ensureRegisterPythonModelTasksImport(dagCode);
  const isDecoratorStyle = next.includes('@dag');
  const isContextManagerStyle = /with\s+DAG\s*\(/.test(next);

  let style: 'decorator' | 'context-manager' | 'imports-only';
  if (isDecoratorStyle) {
    next = injectTasksDecoratorStyle(next);
    style = 'decorator';
  } else if (isContextManagerStyle) {
    next = injectTasksContextManagerStyle(next);
    style = 'context-manager';
  } else {
    style = 'imports-only';
  }

  return { next, style };
}

/**
 * Short preview snippet shown in the confirm modal before writing.
 */
export function buildDagInjectionPreview(
  dagFilePath: string,
  dagId: string,
): string {
  return [
    `File: ${dagFilePath}`,
    '',
    'Will add:',
    '  from _ext_.etl_helper import register_python_model_tasks',
    `  entry_tasks, exit_tasks = register_python_model_tasks("${dagId}", ...)`,
    '',
    'and wire those tasks into the existing DAG dependency chain.',
  ].join('\n');
}
