import type {
  PythonModelCell,
  PythonModelConfig,
} from '@shared/framework/types';

/**
 * Generate the shared python_models/_config.py module.
 * Contains PythonModelConfig dataclass + catalog/namespace helpers.
 * Created once per project.
 */
export function generatePythonModelConfigPy(): string {
  return `"""
Shared configuration for Python models.
Auto-generated by DJ Framework -- DO NOT EDIT.

Uses Trino as reads from and writes to Iceberg tables.
"""

from __future__ import annotations

from dataclasses import dataclass, field


GLUE_CATALOG_VARIABLE = "dj_python_model_glue_catalog"

NAMESPACE_VARIABLE = "dj_python_model_namespace"


def _require_variable(var_name: str) -> str:
    """Read an Airflow Variable, raising if missing, empty, or the literal "None"."""
    from airflow.models import Variable  # noqa: PLC0415
    value = (Variable.get(var_name, default_var=None) or "").strip()
    if not value or value == "None":
        raise ValueError(
            f"Airflow Variable {var_name!r} is not set to a valid value (got {value!r})."
        )
    return value


def get_catalog_name() -> str:
    """Trino/Glue catalog name from the dj_python_model_glue_catalog Variable."""
    return _require_variable(GLUE_CATALOG_VARIABLE)


def get_namespace_name() -> str:
    """Schema/namespace from the dj_python_model_namespace Variable."""
    return _require_variable(NAMESPACE_VARIABLE)


@dataclass(frozen=True)
class PythonModelConfig:
    model_name: str
    namespace: str = field(default_factory=get_namespace_name)
    table_name: str = ""
    model_type: str = "python"
    description: str = ""

    @property
    def table_properties(self) -> dict[str, str]:
        return {
            "python_model_name": self.model_name,
            "python_model_type": self.model_type,
            "python_model_namespace": self.namespace,
            "python_model_table": self.table_name or self.model_name,
            "python_model_description": self.description,
        }
`;
}

/**
 * Generate the shared python_models/_trino_io.py module.
 * Provides Trino connection helpers, DML operations (append, overwrite,
 * overwrite_partition, merge, update), and DDL helpers (create_schema,
 * create_hive_csv_external_table, create_iceberg_table, set_extra_properties,
 * flush_hive_metadata_cache). Always overwritten by the extension -- DO NOT
 * hand-edit the generated file.
 */
export function generateTrinoIoPy(): string {
  return `"""
Shared Trino I/O helpers for python_models.
Auto-generated by DJ Framework -- DO NOT EDIT.

Provides connection construction, SQL execution, and DML operations
(append, overwrite_partition, overwrite_table, merge, update)
used by Python model ETL pipelines.
"""
from __future__ import annotations

import logging
import os
from typing import Any
from collections.abc import Sequence

import trino as trino_client

log = logging.getLogger(__name__)


# ── Connection helpers ──────────────────────────────────────────────

def _var(name: str, default: str = "") -> str:
    """Resolve a config value from env vars, falling back to Airflow Variables."""
    env_val = os.environ.get(name.upper())
    if env_val is not None:
        return env_val
    try:
        from airflow.models import Variable  # noqa: PLC0415
        return Variable.get(name, default_var=default)
    except Exception:
        return default


def _resolve_trino_config() -> dict[str, Any]:
    host = _var("dj_python_model_trino_host")
    return {
        "host": host,
        "port": int(_var("dj_python_model_trino_port", "443")),
        "user": _var("dj_python_model_trino_user"),
        "password": _var("dj_python_model_trino_password"),
    }


def get_trino_connection():
    """Create a Trino DB-API connection from Airflow Variables / env vars."""
    cfg = _resolve_trino_config()
    return trino_client.dbapi.connect(
        host=cfg["host"],
        port=cfg["port"],
        user=cfg["user"],
        http_scheme="https",
        auth=trino_client.auth.BasicAuthentication(cfg["user"], cfg["password"]),
        verify=False,
        session_properties={
            "query_max_run_time": "60m",
        },
        request_timeout=900.0,
    )


# ── Core execute ────────────────────────────────────────────────────


def execute_sql(sql: str) -> None:
    """Execute a DDL/DML statement with no result set to consume."""
    with get_trino_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(sql)


def fetch_value(sql: str):
    """Execute a query and return the first column of the first row (or None)."""
    with get_trino_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(sql)
        row = cursor.fetchone()
        return row[0] if row else None


# ── DML operations ──────────────────────────────────────────────────


def append(table_fqn: str, insert_sql: str) -> None:
    """Plain INSERT INTO -- executes the user's insert SQL as-is."""
    log.info(f"append: inserting into {table_fqn}")
    execute_sql(insert_sql)

def _build_insert_sql(
    table_fqn: str,
    source_query: str,
    columns: Sequence[str] | None = None,
) -> str:
    """Assemble \`INSERT INTO fqn (cols) <source_query>\`.

    \`source_query\` is the row-producing query -- a plain SELECT or a
    WITH ... SELECT. When \`columns\` is given, names are quoted and used
    as the explicit target column list.
    """
    if not source_query:
        raise ValueError("source_query is required to build an insert")
    if columns:
        col_list = ", ".join(f'"{c}"' for c in columns)
        return f"INSERT INTO {table_fqn} ({col_list})\\n{source_query}"
    return f"INSERT INTO {table_fqn}\\n{source_query}"


def _rows_to_values(rows) -> str:
    """Render rows as a Trino \`VALUES\` list: (a, b), (c, d), ..."""
    return ", ".join(
        "(" + ", ".join(_sql_literal(v) for v in row) + ")"
        for row in rows
    )


def _sql_literal(v) -> str:
    """Serialize a single value to a Trino SQL literal."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def overwrite(
    table_fqn: str,
    overwrite_filter: str,
    source_query: str | None = None,
    *,
    columns: Sequence[str] | None = None,
    insert_sql: str | None = None,
) -> None:
    """Overwrite rows matching a filter (Trino SQL).

    If the insert fails, the originals are written back. Provide EITHER \`source_query\`
    (+ optional \`columns\`) OR a fully-formed \`insert_sql\`.
    """
    if insert_sql is None:
        insert_sql = _build_insert_sql(table_fqn, source_query, columns)

    delete_sql = f"DELETE FROM {table_fqn} WHERE {overwrite_filter}"

    # Keep the rows we're about to delete, so we can restore on failure.
    backup_rows = fetch_value(
        f"SELECT * FROM {table_fqn} WHERE {overwrite_filter}",
    ) or []

    log.info(f"overwrite: {delete_sql}")
    execute_sql(delete_sql)
    try:
        execute_sql(insert_sql)
    except Exception:
        log.exception("insert failed; restoring %d rows", len(backup_rows))
        execute_sql(delete_sql)  # clear any partial insert first
        if backup_rows:
            execute_sql(
                f"INSERT INTO {table_fqn} "
                f"VALUES {_rows_to_values(backup_rows)}"
            )
        raise


def overwrite_partition(
    table_fqn: str,
    partition_col: str,
    partition_value: str,
    source_query: str | None = None,
    *,
    columns: Sequence[str] | None = None,
    insert_sql: str | None = None,
) -> None:
    """Overwrite a single partition (wrapper over overwrite())."""
    safe_value = str(partition_value).replace("'", "''")
    overwrite_filter = f""""{partition_col}" = '{safe_value}'"""
    overwrite(
        table_fqn,
        overwrite_filter,
        source_query=source_query,
        columns=columns,
        insert_sql=insert_sql,
    )


def merge(table_fqn: str, merge_sql: str) -> None:
    """Row-level MERGE (upsert) -- executes the user's MERGE SQL."""
    log.info(f"merge: merging into {table_fqn}")
    execute_sql(merge_sql)


# ── DDL operations ──────────────────────────────────────────────────


def create_schema(catalog: str, schema: str) -> None:
    sql = f'CREATE SCHEMA IF NOT EXISTS "{catalog}"."{schema}"'
    log.info(f"create_schema: {sql}")
    try:
        execute_sql(sql)
    except Exception as exc:
        err_name = getattr(exc, "error_name", "") or ""
        if "PERMISSION_DENIED" in err_name or "PERMISSION_DENIED" in str(exc):
            log.warning(
                "create_schema: permission denied for %s.%s, assuming it exists",
                catalog,
                schema,
            )
        else:
            raise


def create_hive_csv_external_table(
    table_fqn: str,
    columns: Sequence[tuple[str, str]],
    external_location: str,
    *,
    skip_header_line_count: int = 1,
) -> None:
    """CREATE TABLE IF NOT EXISTS for a Hive CSV external table over S3."""
    col_defs = ",\\n    ".join(f'"{name}" {ctype}' for name, ctype in columns)
    sql = (
        f"CREATE TABLE IF NOT EXISTS {table_fqn} (\\n    {col_defs}\\n)\\n"
        f"WITH (\\n    external_location = '{external_location}',\\n"
        f"    format = 'CSV',\\n    skip_header_line_count = {skip_header_line_count}\\n)"
    )
    log.info(f"create_hive_csv_external_table: {table_fqn}")
    execute_sql(sql)


def create_iceberg_table(
    table_fqn: str,
    columns: Sequence[tuple[str, str]],
    *,
    partitioning: Sequence[str] = (),
) -> None:
    """CREATE TABLE IF NOT EXISTS for an Iceberg table with optional partitioning."""
    col_defs = ",\\n  ".join(f'"{name}" {ctype}' for name, ctype in columns)
    sql = f"CREATE TABLE IF NOT EXISTS {table_fqn} (\\n  {col_defs}\\n)"
    if partitioning:
        partition_array = ", ".join(f"'{p}'" for p in partitioning)
        sql += f"\\nWITH (\\n  partitioning = ARRAY[{partition_array}]\\n)"
    log.info(f"create_iceberg_table: {sql}")
    execute_sql(sql)


def set_extra_properties(
    table_fqn: str,
    properties: Sequence[tuple[str, str]],
) -> None:
    """Idempotently set Iceberg \`extra_properties\` via ALTER TABLE SET PROPERTIES."""
    keys = ", ".join(f"'{_escape_sql_literal(k)}'" for k, _ in properties)
    vals = ", ".join(f"'{_escape_sql_literal(v)}'" for _, v in properties)
    sql = (
        f"ALTER TABLE {table_fqn} SET PROPERTIES "
        f"extra_properties = MAP(ARRAY[{keys}], ARRAY[{vals}])"
    )
    log.info(f"set_extra_properties: {sql}")
    execute_sql(sql)


def _escape_sql_literal(value: str) -> str:
    """Escape single quotes for embedding a string in a SQL literal."""
    return value.replace("'", "''")


def flush_hive_metadata_cache(
    catalog: str,
    schema_name: str,
    table_name: str,
) -> None:
    """Flush the Hive connector metadata cache for one table.

    Wraps \`CALL <catalog>.system.flush_metadata_cache(...)\`, which requires
    named parameters. Safe no-op if metadata caching is disabled on the cluster.
    """
    call_sql = (
        f'CALL "{catalog}".system.flush_metadata_cache('
        f"schema_name => '{schema_name}', table_name => '{table_name}')"
    )
    log.info("flush_hive_metadata_cache: %s", call_sql)
    execute_sql(call_sql)


def update(table_fqn: str, set_clause: str, where_clause: str) -> None:
    """Standalone conditional UPDATE."""
    update_sql = f"UPDATE {table_fqn} SET {set_clause} WHERE {where_clause}"
    log.info(f"update: {update_sql}")
    execute_sql(update_sql)
`;
}

/**
 * Generate the shared python_models/_model_tasks.py module.
 * Provides topological-level sorting of models by their dependency map.
 * Always overwritten by the extension -- DO NOT hand-edit the generated file.
 */
export function generatePythonModelTasksPy(): string {
  return `"""Shared topological model-task computation for Python model orchestration.

Used by both the Airflow DAG helper (dags/_ext_/etl_helper.py) and the
K8s pod entrypoint (dags/python_models/entrypoint.py).

Auto-generated by DJ Framework -- DO NOT EDIT.
"""
from __future__ import annotations


def compute_model_tasks_from_deps(
    ids: list[str], deps: dict[str, list[str]]
) -> list[list[str]]:
    """Topological-level sort by dependency map.

    Args:
        ids: List of model identifiers.
        deps: Mapping of model_id -> list of dependency model_ids (filtered
              to only include ids within the provided set).

    Returns:
        List of model-task batches where each batch is a list of model_ids
        that can execute in parallel once all prior batches have completed.
    """
    remaining = set(ids)
    resolved: set[str] = set()
    model_task_batches: list[list[str]] = []
    while remaining:
        model_tasks = [
            mid for mid in remaining if all(d in resolved for d in deps.get(mid, []))
        ]
        if not model_tasks:
            raise RuntimeError(f"Dependency cycle detected among models: {remaining}")
        model_task_batches.append(sorted(model_tasks))
        resolved.update(model_tasks)
        remaining -= set(model_tasks)
    return model_task_batches
`;
}

// ── Jupytext-style notebook <-> .py round-tripping ──────────────────
//
// .python.py is the source of truth. Cells are delimited with jupytext
// "percent" markers:
//   # %%              -> code cell
//   # %% [markdown]   -> markdown cell (body lines stored as "# " comments)
//   # %% [raw]        -> raw cell
// A .py with no markers is treated as a single code cell and serializes
// back to a clean module (no markers), so real hand-authored modules
// round-trip unchanged.

const CELL_MARKER_RE = /^# %%(?:\s+\[(markdown|raw)\])?\s*$/;

/** Split a text blob into nbformat-style source lines (trailing \n on all but the last). */
function toSourceArray(text: string): string[] {
  if (text === '') {
    return [];
  }
  const lines = text.split('\n');
  return lines.map((line, i) => (i < lines.length - 1 ? `${line}\n` : line));
}

/** Join a cell's source (array or string) into a single text blob. */
function cellText(cell: PythonModelCell): string {
  return Array.isArray(cell.source) ? cell.source.join('') : cell.source;
}

/** Strip trailing whitespace / blank lines from the end of a blob. */
function trimTrailingNewlines(text: string): string {
  return text.replace(/\s+$/g, '');
}

/** Ensure the blob ends with exactly one trailing newline. */
function ensureTrailingNewline(text: string): string {
  return text.endsWith('\n') ? text : `${text}\n`;
}

function makeCodeCell(text: string): PythonModelCell {
  return {
    cell_type: 'code',
    execution_count: null,
    metadata: {},
    outputs: [],
    source: toSourceArray(text),
  };
}

function makeMarkdownCell(
  text: string,
  metadata: Record<string, unknown> = {},
): PythonModelCell {
  return {
    cell_type: 'markdown',
    metadata,
    source: toSourceArray(text),
  };
}

/**
 * A derived, notebook-only cell (e.g. the model header) that must never be
 * written back into the .python.py source of truth.
 */
function isNotebookOnlyCell(cell: PythonModelCell): boolean {
  const meta = cell.metadata as Record<string, unknown> | undefined;
  if (meta && meta.dj_notebook_only === true) {
    return true;
  }
  return cellText(cell).startsWith('# Python Model:');
}

/**
 * Drop derived, notebook-only cells (the model header) from a cell list so the
 * remaining cells can be persisted into .python.json without the regenerated
 * header leaking into the stored snapshot.
 */
export function stripNotebookOnlyCells(
  cells: PythonModelCell[],
): PythonModelCell[] {
  return cells.filter((cell) => !isNotebookOnlyCell(cell));
}

/**
 * Parse a .python.py module into notebook cells using jupytext percent
 * markers. A module with no markers becomes a single code cell.
 */
export function parsePythonToCells(pyCode: string): PythonModelCell[] {
  const lines = pyCode.split('\n');
  const markerIdxs: number[] = [];
  lines.forEach((line, i) => {
    if (CELL_MARKER_RE.test(line)) {
      markerIdxs.push(i);
    }
  });

  if (markerIdxs.length === 0) {
    return [makeCodeCell(trimTrailingNewlines(pyCode))];
  }

  const cells: PythonModelCell[] = [];

  // Content before the first marker becomes a leading code cell.
  if (markerIdxs[0] > 0) {
    const preamble = trimTrailingNewlines(
      lines.slice(0, markerIdxs[0]).join('\n'),
    );
    if (preamble.trim() !== '') {
      cells.push(makeCodeCell(preamble));
    }
  }

  for (let m = 0; m < markerIdxs.length; m++) {
    const markerLine = lines[markerIdxs[m]];
    const bodyStart = markerIdxs[m] + 1;
    const bodyEnd =
      m + 1 < markerIdxs.length ? markerIdxs[m + 1] : lines.length;
    const bodyLines = lines.slice(bodyStart, bodyEnd);
    const kind = markerLine.match(CELL_MARKER_RE)?.[1];

    if (kind === 'markdown') {
      const md = bodyLines
        .map((line) =>
          line.startsWith('# ') ? line.slice(2) : line === '#' ? '' : line,
        )
        .join('\n');
      cells.push(makeMarkdownCell(trimTrailingNewlines(md)));
    } else if (kind === 'raw') {
      cells.push({
        cell_type: 'raw',
        metadata: {},
        source: toSourceArray(trimTrailingNewlines(bodyLines.join('\n'))),
      });
    } else {
      cells.push(makeCodeCell(trimTrailingNewlines(bodyLines.join('\n'))));
    }
  }

  return cells;
}

/**
 * Serialize notebook cells back into a .python.py module. Notebook-only cells
 * (the derived header) are skipped. A single code cell produces a clean module
 * with no markers; otherwise jupytext percent markers delimit the cells.
 */
export function serializeCellsToPython(cells: PythonModelCell[]): string {
  const emittable = cells.filter((cell) => !isNotebookOnlyCell(cell));

  if (emittable.length === 0) {
    return '';
  }

  if (emittable.length === 1 && emittable[0].cell_type === 'code') {
    return ensureTrailingNewline(trimTrailingNewlines(cellText(emittable[0])));
  }

  const blocks = emittable.map((cell) => {
    const body = trimTrailingNewlines(cellText(cell));
    if (cell.cell_type === 'markdown') {
      const commented = body
        .split('\n')
        .map((line) => (line.length > 0 ? `# ${line}` : '#'))
        .join('\n');
      return `# %% [markdown]\n${commented}`;
    }
    if (cell.cell_type === 'raw') {
      return `# %% [raw]\n${body}`;
    }
    return `# %%\n${body}`;
  });

  return ensureTrailingNewline(blocks.join('\n\n'));
}

/**
 * Build the in-memory notebook cell list for display: a derived, notebook-only
 * header markdown cell followed by the cells parsed from the .py source.
 */
export function buildNotebookCells(
  pyCode: string,
  config: PythonModelConfig,
): PythonModelCell[] {
  return [buildHeaderCell(config), ...parsePythonToCells(pyCode)];
}

function buildHeaderCell(config: PythonModelConfig): PythonModelCell {
  const modelId = `python__${config.group}__${config.topic}__${config.name}`;
  const dags = config.dags ?? [];
  const dagsStr = dags.length > 0 ? dags.join(', ') : '(none)';
  return {
    cell_type: 'markdown',
    metadata: { dj_notebook_only: true },
    source: [`# Python Model: ${modelId}\n`, `**DAGs**: ${dagsStr}`],
  };
}

/**
 * Generate a clean, marker-delimited scaffold .python.py for a new model.
 * Import is side-effect free: no top-level context dict and no runner call.
 */
export function generatePythonModelScaffoldPy(
  config: PythonModelConfig,
): string {
  return serializeCellsToPython(buildScaffoldCodeCells(config));
}

function buildScaffoldCodeCells(config: PythonModelConfig): PythonModelCell[] {
  const { name, group, topic } = config;
  const description = config.description ?? '';
  const dags = config.dags ?? [];
  const namespace = config.namespace ?? 'python';
  const tableName = config.table_name ?? name;
  const outputType = config.output_type ?? 'iceberg';
  const modelId = `python__${group}__${topic}__${name}`;
  const dagsStr = dags.length > 0 ? dags.join(', ') : '(none)';

  const imports = [
    'from datetime import datetime',
    'import io',
    'import json',
    'import logging',
  ];
  if (outputType === 's3') {
    imports.push('import boto3');
  }

  const variableEntries: Record<string, string> = {
    name,
    group,
    topic,
    description,
    ...(config.variables ?? {}),
  };
  const variableLines = Object.entries(variableEntries)
    .map(([key, value]) => `    "${key}": "${value}",`)
    .join('\n');

  const headerCell = [
    '"""',
    `Python Model: ${modelId}`,
    `DAGs: ${dagsStr}`,
    '"""',
    ...imports,
    '',
    'from python_models._trino_io import execute_sql, overwrite_partition',
    'from python_models._config import PythonModelConfig, get_catalog_name',
    '',
    'log = logging.getLogger(__name__)',
    '',
    'OUTPUT_CONFIG = PythonModelConfig(',
    `    model_name="${name}",`,
    `    namespace="${namespace}",`,
    `    table_name="${tableName}",`,
    '    model_type="python",',
    `    description="${description}",`,
    ')',
  ].join('\n');

  const inputVarsCell = ['INPUT_VARIABLES = {', variableLines, '}'].join('\n');

  const extractCell = [
    'def extract(context: dict) -> None:',
    '    """Fetch data from source and stage into Trino."""',
    "    log.info(f\"Extracting for {context['ds']}...\")",
    '    raise NotImplementedError("Implement extract()")',
  ].join('\n');

  const transformCell = [
    'def transform_and_load(context: dict) -> None:',
    '    """Run SQL transformations and load into target table."""',
    '    ds = context["ds"]',
    '    table = f"{get_catalog_name()}.{OUTPUT_CONFIG.namespace}.{OUTPUT_CONFIG.table_name}"',
    '',
    '    insert_sql = f"""',
    '        INSERT INTO {table}',
    '        SELECT',
    '            -- enumerate columns explicitly',
    "            '{ds}' AS portal_partition_daily",
    '        FROM iceberg_catalog.stg_tmp.TODO_staging_table',
    '    """',
    '',
    '    overwrite_partition(table, "portal_partition_daily", ds, insert_sql=insert_sql)',
    '    log.info(f"Loaded partition {ds} into {table}")',
  ].join('\n');

  const cleanupCell = [
    'def cleanup(context: dict) -> None:',
    '    """Drop staging tables or temporary resources."""',
    '    pass',
  ].join('\n');

  const runEtlCell = [
    'def run_etl(context: dict):',
    '    """Main ETL orchestrator."""',
    '    extract(context)',
    '    transform_and_load(context)',
    '    cleanup(context)',
  ].join('\n');

  return [
    makeCodeCell(headerCell),
    makeCodeCell(inputVarsCell),
    makeCodeCell(extractCell),
    makeCodeCell(transformCell),
    makeCodeCell(cleanupCell),
    makeCodeCell(runEtlCell),
  ];
}

/**
 * Convert cells to a Jupyter notebook (.python.ipynb) JSON string.
 */
export function cellsToNotebook(cells: PythonModelCell[]): string {
  const nbCells = cells.map((cell) => {
    const base: Record<string, unknown> = {
      cell_type: cell.cell_type,
      metadata: cell.metadata ?? {},
      source: cell.source,
    };
    if (cell.cell_type === 'code') {
      base.execution_count = cell.execution_count ?? null;
      base.outputs = cell.outputs ?? [];
    }
    return base;
  });

  const notebook = {
    cells: nbCells,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.9.0',
      },
    },
    nbformat: 4,
    nbformat_minor: 2,
  };

  return JSON.stringify(notebook, null, 2);
}
